# Generated by Django 4.1.7 on 2023-05-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0017_alter_projet_avisn_alter_projet_avisp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
